name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyPDF2
        pip install pyinstaller
    
    - name: Build EXE
      run: |
        pyinstaller --name="PDF页面顺序反转工具" --windowed --onefile --clean 124.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF页面顺序反转工具
        path: dist/PDF页面顺序反转工具.exe 